[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
NVTX = "5da4648a-3479-48b8-97b9-01cb529c0a1f"
